version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/bill-gates
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 180
      runas: ubuntu

